- pomegranate/BayesianNetwork.pyx
- pomegranate/base.pyx
- pomegranate/distributions.pyx
- setup.py
- tests/test_distributions.py
Fixes issue #19 
A segfault was raised due to states renaming distributions to give them unique identifiers for the Bayesian network data slicing. Instead of renaming, they are identified by a hash on the distribution object itself. This may need to be reworked should distribution tying for Bayesian networks be added, but it works for now and is more justified than the hack before.
> Fixed segfault issue on Anaconda distribution

- .travis.yml
- benchmarks/benchmark_hmm.py
- pomegranate/base.pxd
- pomegranate/base.pyx
- pomegranate/distributions.pyx
- pomegranate/fsm.pyx
- pomegranate/hmm.pyx
- requirements.txt
- setup.py
- tests/test_hmm_training.py
> [MRG] Multithreaded HMM training

- benchmarks/benchmark_hmm.py
- pomegranate/hmm.pyx
More updates to make multithreading more efficient. Now the internal expected transitions matrix has been reduced down to a vector for sparse format. This reduces the amount of time spent with the gil acquired at the end of each round. Also, improvements have been made to `model.log_probability`, which seems to be the primary bottleneck.
> [MRG] hmm sparse expected transition matrix

- pomegranate/hmm.pyx
In response to #74, when you concatenate models there is the option to add a suffix or prefix to all elements of the incoming model.
> ENH concatenate updated

- pomegranate/distributions.pyx
- pomegranate/hmm.pyx
Hi,
This fixes a memory leak I encounter when an HMM object is baked more than once, like in the code below, where `model.copy()` also performs a `bake()` behind the scenes.
```python
models = []
for _ in xrange(5):
model = HiddenMarkovModel()
state = State(DiscreteDistribution({"a" : 0.25, "b": 0.25, "c" : 0.25, "d": 0.25}), name="a")
model.add_transition(model.start, state, 1.0)
model.add_transition(state, state, 1.0)
model.add_transition(state, model.end, 1.0)
model.bake()
models.append(model)
def concat_models(models):
new_model = models[0].copy()
for idx in xrange(1, len(models)):
model_copy = models[idx].copy()
new_model.concatenate(model_copy, str(idx))
new_model.bake()
return new_model
while True:
model = concat_models(models)
```
> fix memory leak in hmm.bake() and discretedistribution.encode()

- pomegranate/MarkovChain.pyx
- pomegranate/NaiveBayes.pyx
- pomegranate/base.pyx
- pomegranate/distributions.pyx
- pomegranate/gmm.pyx
- pomegranate/hmm.pyx
- tests/test_distributions.py
- tests/test_gmm.py
- tests/test_hmm.py
- tests/test_markov_chain.py
- tests/test_naive_bayes.py
This PR follows up issue https://github.com/jmschrei/pomegranate/issues/153
It adds the methods `__getstate__` and `__getstate__` to GeneralMixtureModel and HiddenMarkovModel to make them 'picklable'.
I had to modify the automatic name generation of State to make sure we always have unique state names (unless overriden by user). Otherwise, deserialization fails on name collision. This fix relies on the uuid library which is part of python standard library.
There are two very simple regression tests to check that pickle doesn't crash. I didn't test if the reloaded value is identical to the original one because json tests should be sufficient. And I have no clue how to properly compare the objects :-) .
> Add support for serialization in GMM and HMM

- pomegranate/BayesianNetwork.pyx
- pomegranate/FactorGraph.pyx
- pomegranate/base.pyx
- pomegranate/distributions.pxd
- pomegranate/distributions.pyx
- pomegranate/hmm.pyx
Implements the backend to support structure learning algorithms efficiently by converting all observations into a set of integer keys and operating at the C level. Currently only supports chow-liu tree learning.
> bayesian network structure learning

- README.md
I added a brief list of the dependencies to the readme; took me awhile to get everything that was needed since errors that they're missing aren't necessarily thrown until test-time.
> add list of dependencies to readme

- pomegranate/base.pxd
- pomegranate/base.pyx
Following up https://github.com/jmschrei/pomegranate/issues/156 this is a first little contribution to code style.
There are still warnings from the linter (pycharm) about undefined `Model.parameters` not being defined, GraphModel not implementing all abstract methods and `GraphModel.dense_transition_matrix` using undefined attributes.
> beautification

- tests/test_distributions.py
Fixed the distribution tests to pass pep8.
Summary of what changed: 
- removed star imports
- removed random module that was unused
- converted tabs to 4 spaces
- removed extraneous whitespace around lots of parameter arguments
> make distribution tests pep8

- pomegranate/NaiveBayes.pyx
found another place encode was erroneously used, so i fixed it.
> change deprecated encode to bake in naive bayes

- pomegranate/BayesianNetwork.pyx
- pomegranate/distributions.pyx
- tests/test_bayes_net.py
This PR fixes three different but related issues. The first is in the case when a certain parent set in a conditional probability table has no counts during training, it will assign a uniform distribution to each of the values of that variable instead of crashing. The second is that when a Bayesian network is trained, it did not update the underlying factor graph appropriately. This remakes the factor graph after each update, which is the most efficient way of updating it. The third is that during the message passing scheme with a Bayesian network with many impossible scenarios (0's in the discrete distributions or CPTs) the messages may be inconsistent, such that one message is certain one value is happening, but another message says the opposite. In these cases the messages would cancel …
> FIX Bayes Net belief propogation

- pomegranate/BayesianNetwork.pyx
- pomegranate/base.pxd
- pomegranate/base.pyx
- pomegranate/bayes.pxd
- pomegranate/bayes.pyx
- pomegranate/distributions.pyx
- pomegranate/gmm.pyx
- pomegranate/hmm.pyx
- tests/test_distributions.py
- tests/test_hmm.py
Explicitly remove the `_log_probability` and `_mv_log_probability` methods, using exclusively `_v_log_probability` to calculate a vector of log probabilities. Renames `_v_log_probability` to `_log_probability`. Follows the scipy format of returning either a single number or an array of log probabilities given the input. This speeds up log probability calculations across almost all models.
> [MRG] Clean up log probability calculation internals

- .gitignore
- .travis.yml
- README.md
- appveyor.yml
- appveyor/install.ps1
- appveyor/run_with_env.cmd
- dev-requirements.txt
- pomegranate/__init__.py
- requirements.txt
- setup.py
Installation can be tedious on Windows and OS X due to the need for a C compiler. This pull request sets up AppVeyor and Travis CI to build precompiled wheels. These wheels can be uploaded directly to PyPI. Wheels are built for Python 2.7, 3.4, 3.5, and 3.6 on Windows x86, x64, and OS X (Linux should still build from source).
Changes:
- Set up AppVeyor to install, test, and build wheels on Windows
- Changed Travis CI script to include OS X and to build wheels
- Removed requirement for Numpy to be installed prior to installation (`np.get_includes()`)
- Removed Cython runtime requirement (required only during setup)
Action required for maintainers if accepted:
- Set up AppVeyor to build this repo
- Update the API key in the GitHub releases deployment (or remove the deployment altogether)
- …
> Automatically building Python Wheels

- pomegranate/distributions.pyx
- tests/test_distributions.py
The Conditional Probability Tables method for sampling seems broken to me.
1. I get this error, TypeError: 'odict_keys' object does not support indexing
2. There is a  dict as a default value (which is mutated). This means the 2nd time I call `sample()`, the value of `parent_values` used is the one modified internally after calling `sample()` for the first time.
I also added a test.
> Fix sampling from Conditional Probability Tables

- pomegranate/hmm.pyx
* Previously, calling `predict` was the same as calling `viterbi` on a
HMM object. This behaviour has since changed, but the docs stayed the
same.
* This commit updates the inline docstring of the `predict` function of
`HMM` in order to reflect the new situation.
* Fixes #245.
Signed-off-by: mr.Shu <mr@shu.io>
> docs: Fix the docstring of the HMM's `predict`

- setup.py
Hello,
What this PR does:
- verbose mode on HMM also recalls the number of iterations
- .pxd files are distributed in binary packages as well (python setup.py bdist, pip install .), this is needed to use custom distributions
> minor modifications

- pomegranate/NaiveBayes.pyx
When I was looking through the API documentation for NaiveBayes on ReadTheDocs, I noticed that:
1. The pseudocount parameter documentation for from_samples was tabbed incorrectly (spaces
rather than tabs), inconsistent with the rest of the docs, which broke the HTML version.
2. There was an n_components parameter, which seems to have been removed and is now
inferred automatically.
3. The n_jobs parameter wasn't documented (but was in e.g., fit).
So I thought I'd fix the above issues (tabbed, removed + added) when I encountered them.
> Correcting code documentation for NaiveBayes.

- pomegranate/hmm.pyx
- tests/test_hmm.py
Added the option end_state=False to hmm.from_samples. If true, the HMM will also train to determine which states are likely to be the end of the sequence.
> [MRG] Added option for explicit end states to hmm.from_samples()

- pomegranate/BayesClassifier.pyx
- pomegranate/BayesianNetwork.pyx
- pomegranate/bayes.pyx
- pomegranate/utils.pyx
This adds the n_jobs parameter to the vectorized prediction functions, speeding them up linearly with the number of threads in cases where large amounts of data are being crunched. For an example, a 10 node Bayesian network calculating the log probability of ~100,000 points:
```
Bayesian Network Log Probability (n_jobs=1)
-8317751.26947 25.122713089
Bayesian Network Log Probability (n_jobs=2)
-8317751.26947 18.0607879162
Bayesian Network Log Probability (n_jobs=4)
-8317751.26947 5.8684720993
```
> [MRG] Add n_jobs parameter to predict methods

- MANIFEST.in
Attempt to fix https://github.com/jmschrei/pomegranate/issues/282.
Remaining .so file are not included in the source distributions.
> don't include leftover .so files in sdist packages

- pomegranate/kmeans.pyx
This reformulates the k-means equation from ||a-b||^{2} to ||a||^{2} + ||b||^{2} - 2 a*b, which allows for the caching of ||b||^{2} (the centroid norms) as well as using dgemm from blas to solve the matrix multiplication. Significant speedups in fitting. Also a changelog is introduced.
> [MRG] Faster k-means

- docs/MarkovChain.rst
> Fix typo in MarkovChain

- docs/Distributions.rst
Remove `weights=[...]` in example.
> Fix typo in distributions

- docs/whats_new.rst
- pomegranate/hmm.pyx
Adds support for semi-supervised HMM training. This means in particular that HMMs can be fit to a mixture of fully labeled and completely unlabeled sequences, not that the sequences can be partially labeled. Unlabeled sequences can be specified using `None` instead of a list of labels. Labels can now also be strings in addition to passing in the state object as before. The `from_samples` method now allows you to do semi-supervised learning if you also pass in the corresponding `state_names` list. It will first do a supervised initialization of the emission distributions, followed by semi-supervised updates. You can choose to do semi-supervised updates with either Baum-Welch or the Viterbi algorithm for the unsupervised part by specifying the algorithm.
> [MRG] Semi-supervised HMM training

- docs/whats_new.rst
- pomegranate/BayesianNetwork.pyx
This speedup comes by reducing the dataset from redundant samples to a set of non-redundant samples weights according to the number of times they occur in the original dataset. Frequently the actually observed items in a dataset are highly redundant even if the space of possibilities is large. This automatically generates a new non-redundant dataset, resulting in potentially massive speedups when doing structure learning (examples to follow.)
> [MRG] Bayesian Network Structure Learning speedup

- pomegranate/BayesianNetwork.pyx
Fixes: https://github.com/jmschrei/pomegranate/issues/320
More details are here: https://github.com/jmschrei/pomegranate/issues/320#issuecomment-330333122
> Rename variable to avoid overriding function argument

- requirements.txt
Networkx 2.0 changed the behavior of graph.nodes() to produce a NodeView
(which cannot be numerically indexed) instead of a list. See, e.g.
https://networkx.github.io/documentation/networkx-1.10/_modules/networkx/classes/graph.html
https://networkx.github.io/documentation/networkx-2.0/_modules/networkx/classes/graph.html
It's a bummer.
The simplest fix is to require a pre-2.0 version of networkx, which is
all this patch does.
The specific place where this crashes is in hmm.pyx line 734 and 735:
```python
prestates = self.graph.nodes()
indices = { prestates[i]: i for i in range(len(prestates)) }
```
doesn't work because prestates[i] doesn't work, because prestates isn't a list under networkx 2.0.
I have not researched how much work it would be to rewrite this such that it's networkx 2.0 …
> Specify networkx version <2.0.

- docs/minibatch.rst
- docs/ooc.rst
- docs/whats_new.rst
- pomegranate/BayesClassifier.pyx
- pomegranate/NaiveBayes.pyx
- pomegranate/gmm.pyx
- pomegranate/hmm.pyx
- pomegranate/kmeans.pyx
- tests/test_gmm.py
- tests/test_hmm.py
This PR adds support for minibatching to iterative models. This support adds in two main features: (1) automatically summarizing minibatches but only updating model parameters after viewing the entire dataset, useful for out of core computations using memory maps where you can't load up the full dataset, and (2) resizing the epochs so that after a certain number of batches you update model parameters, even before seeing the entire dataset. This is done through the addition of `batch_size` and `batches_per_epoch` to the `fit` and `from_samples` methods of the appropriate models.
> [WIP] Add minibatching support

- pomegranate/gmm.pyx
The docstrings in gmm.pyx use spaces instead of tabs for the pseudocounts description which breaks the rendering of the documentation (see e.g. http://pomegranate.readthedocs.io/en/latest/GeneralMixtureModel.html#pomegranate.gmm.GeneralMixtureModel.fit). This PR fixes this issue.
> Fixed tabbing issue in pseudocount documentation

- docs/whats_new.rst
- pomegranate/hmm.pyx
- tests/test_hmm.py
When using `HiddenMarkovModel.from_samples()` with `DiscreteDistribution` and passing custom labels, if name attribute is left to None a TypeError will be raised from the concatenation with string.
- Cast `name` to str to prevent "NoneType + str" TypeError when name is None
- Add test case to prevent regression
> Fix TypeError in HiddenMarkovModel.from_samples()

- docs/whats_new.rst
- pomegranate/base.pyx
- pomegranate/distributions.pxd
- pomegranate/distributions.pyx
- pomegranate/kmeans.pyx
- pomegranate/utils.pxd
- pomegranate/utils.pyx
- tests/test_distributions.py
- tests/test_gmm.py
- tests/test_kmeans.py
- tests/test_naive_bayes.py
Added in missing value support for most probability distributions (except JointProbabilityTable, ConditionalProbabilityTable, and DirichletDistribution), k-means clustering, and all compositional models based off of the probability distributions.
Missing values should be indicated using `numpy.nan` in the place of the missing value. The implementations assume missing at random (MAR) missingness, and make updates simply by ignoring the value when calculating sufficient statistics. In the case of univariate distributions this simply means ignoring the missing values. In the case of multivariate Gaussians, this means calculating dot products only on pairs of values that both exist and calculating appropriate summations. Care was taken to make it so that when extra calculations needed to be …
> [MRG] Add missing value support for models

- docs/whats_new.rst
- pomegranate/BayesianNetwork.pyx
- pomegranate/distributions.pyx
- tests/test_bayes_net.py
- tests/test_distributions.py
This PR adds missing value support for fitting Bayesian networks, calculating probabilities of samples, and learning the structure of the network. This means that one can learn the structure of a Bayesian network on data sets with missing values now.
> [MRG] BayesianNetwork missing value support

- setup.py
If someone installs pomegranate into site-libraries using the
traditional command of "python setup.py install", the sources will
install as a zipped egg without this option.  Current cython will not
work with cimport from the zipped file.
With this change, users will be protected from seeing this error when
installing in this way.
> Add zip_safe=False to setup.py

- Makefile
- docs/whats_new.rst
- tutorials/Tutorial_3_Hidden_Markov_Models.ipynb
This Makefile will invoke build, install, test, and uninstall on
conda environments for python 2.7 and 3.6.
An nbtest target to use the "jupyter nbconvert --execute" functionality
to find any errors in example and tutorial notebooks.
A minor change to tutorials/Tutorial_3_Hidden_Markov_Models.ipynb
sets the kernelspec to be python2 similar to the other notebooks.
> Add Makefile for convenience in development

- pomegranate/bayes.pyx
- pomegranate/kmeans.pyx
In bayes.pyx and gmm.pyx, use sum(weights) instead of weights.sum() in
__init__() to permit lists to be passed in.
> Change init in bayes and gmm to use sum(weights)

- pomegranate/NaiveBayes.pyx
- pomegranate/base.pyx
- pomegranate/gmm.pyx
- tests/test_hmm.py
This patch set allows GeneralMixtureModels to be used with
HiddenMarkovModel.from_json() and adds a test.
It is a bit of a mystery why the GeneralMixtureModel class is not in
scope already.
> Add test for hmm using gmm from_json

- pomegranate/bayes.pyx
Hello,
Thank you for the great software. Recently, I found my code using pomegranate consume a lot of memory, usually more than 100 GiB, after thousands of calls to `hmm.viterbi()`. This change fixes the problem, and its memory footprint stays at a pretty stable level. Can you reflect this patch in your future release?
> Memory leak in BayesModel._log_probability

- pomegranate/distributions/GammaDistribution.pyx
At the moment, sampling from the gamma distribution simply ignores the parameter
`n` and always returns a single sample from the distribution
> Fix sampling of Gamma Distributions

- pomegranate/hmm.pyx
I think you forgot a few zeros when defining the distributions in the example. I fixed those typos and recomputed the log-likelihood based on the new values. Also changed the print statement to be python 3 compatible.
> Fix typos in `HiddenMarkovModel` doc string example 

- docs/BayesianNetwork.rst
- docs/Distributions.rst
- docs/GeneralMixtureModel.rst
- docs/HiddenMarkovModel.rst
- docs/MarkovChain.rst
- docs/NaiveBayes.rst
This will save time of multiple readers reading the documentation (available on github or readthedocs)
> corrected links of tutorial's jupyter notebooks in some rst files of docs

- MANIFEST.in
Ensures that .pyx files are included in the source distribution, and so pomegranate can then be built from source on systems where cython is present. Resolves #333.
> Add .pyx to MANIFEST.in

- docs/gpu.rst
The version of this function with a leading underscore is only available to Cython code.
> Correct spelling of is_gpu_enabled in documentation

- pomegranate/BayesianNetwork.pyx
This improves running time when a lot of rows are the same due to missing values, such as in the example at https://github.com/jmschrei/pomegranate/issues/589#issuecomment-509419374.
Dataset reduction still adds overhead though, so even with these improvements it's not yet clear whether `reduce_dataset=True` or `reduce_dataset=False` will be faster for our particular data set.
> Make reduce_dataset option work with missing values

- pomegranate/kmeans.pyx
`total_dist` was being used (via the `+=` operator) while it was still initialized to a garbage value. At the same time, `pdist` was being unnecessarily initialized at the beginning of the function only to be initialized later before it is used. So I'm guessing that you meant to put the `= 0.0` on the declaration of `total_dist` but accidentally put it on `pdist` instead.
> Fix return value of Kmeans.summarize

- pomegranate/distributions/distributions.pyx
Just a few lines above this, these variables are already defined to the same values they are being set to here.
> Fix copy-paste error in MultivariateDistribution.log_probability

- pomegranate/kmeans.pyx
This change replaces an unnecessary list allocation and copy with an in-place truncation in the Kmeans code. It also updates the documentation for centroid initialization to account for the `kmeans||` initialization method introduced in 7bbad81.
> Minor Kmeans update

- pomegranate/utils.pxd
- pomegranate/utils.pyx
Bayes net training is about 35% faster when `isnan` is inlined, which makes sense because `npy_isnan` was designed to be an inline function.
Test program:
```
from random import random
X = np.round(np.random.rand(10000, 16))
train = delayed(BayesianNetwork)().from_samples(X)
print(Benchmark(wall_time=True, cpu_time=True, repeat=3)(train))
```
Non-inline `isnan`:
```
mean   8.369287  8.361042
max    8.488417  8.471947
std    0.103549  0.112760
```
Inline `isnan`:
``` …
```
> Make the utils.isnan function inline

- pomegranate/BayesianNetwork.pyx
This speeds up exact Bayes net training by up to 34% when there is little to no variability in the data.
Test program:
```
X = np.zeros([10000, 17])
train = delayed(BayesianNetwork)().from_samples(X, algorithm='exact')
```
Before:
```
mean   6.998546  6.838988
max    7.118689  6.925751
std    0.110920  0.098881
```
After:
```
mean   4.597856  4.502262
max    4.603789  4.547125
std    0.005501  0.048928
```
The speed improvement diminishes as variability in the training dataset increases. If 5% of the zeroes are replaced with ones at random, the speed improvement drops to about 17%, and if 10% of the zeroes are replaced with ones at random, the speed …
> Construct the parent subset more efficiently in ParentGraph.__getitem__

- pomegranate/BayesianNetwork.pyx
As the scoring function in pomegranate depends on the number of states for a variable to calculate the score which is optimised. The calculation will be incorrect if the number of states which are assumed is incorrect, and therefore a suboptimal structure may be returned. 
This pull request is a documentation for the limitation.
> Include disclaimer if not all the states for a random variable appear

- pomegranate/distributions/ConditionalProbabilityTable.pyx
- pomegranate/distributions/DiscreteDistribution.pyx
- pomegranate/distributions/JointProbabilityTable.pyx
- pomegranate/distributions/MultivariateGaussianDistribution.pyx
- pomegranate/gmm.pyx
The calloc function is guaranteed to zero out the memory before returning a pointer to it.
> Remove unnecessary calls to memset after calloc

- pomegranate/distributions/DiscreteDistribution.pyx
- pomegranate/hmm.pyx
- pomegranate/utils.pyx
Sometimes BayesianNetwork ignored a NaN value in the input when trained from samples, because `DiscreteDistribution._log_probability` checked only for Python floats, not also NumPy floats.
Also did some refactoring.
> Refactored and fixed checking NaNs

- pomegranate/BayesianNetwork.pyx
This decreases the time it takes to train a Chow-Liu net by about 5%. (Tuples, being immutable, are expensive to manipulate.)
Test program:
```
from random import random
X = np.round(np.random.rand(10000, 100))
train = delayed(BayesianNetwork)().from_samples(X, algorithm='chow-liu')
print(Benchmark(wall_time=True, cpu_time=True, repeat=3)(train))
```
Before:
```
mean   9.900260  9.883265
max    9.965771  9.914445
std    0.073636  0.037711
```
After:
``` …
```
> Store Chow-Liu structure in lists while it is being built

- pomegranate/BayesianNetwork.pyx
It looks like the variable d was accidentally introduced here from a copy and paste.
> Remove unused variable d from BayesianNetwork.from_structure

- MANIFEST.in
Include the LICENSE file, as the MIT license requires it be included in all copies of the software.  Also simplify the `MANIFEST.in` file a little.
> Include LICENSE file

- pomegranate/base.pyx
Small change made, in order to deal with deprecation warning: YAMLLoadWarning, when calling from_yaml e.g. for an HMM instantiation from yaml string
"default loader is unsafe" so I offer to replace it by yaml.Loader,
(see also https://msg.pyyaml.org/load)
(one of my first pull requests, plz be gentle =))
> Deprecation warning YAMLLoadWarning: Add Loader argument for yaml loading

- pomegranate/distributions/DiscreteDistribution.pxd
- pomegranate/distributions/DiscreteDistribution.pyx
The default implementation of Model.probability exponentiates the result of the model's log_probability function. However, DiscreteDistribution already keeps copies of its probability table in both log space and non-log space, so we can skip the exponentiation and just read from the non-log-space table that we already have.
This patch speeds up Bayes net predictions by about 15%, which is a big deal when the Bayes net is large, complex, and repeatedly queried.
Test program:
```
print(Benchmark(wall_time=True, cpu_time=True, …
```
> Add fast path to get non-log discrete distribution probabilities

- benchmarks/benchmark_distributions.py
- benchmarks/benchmark_hmm.py
- docs/callbacks.rst
- docs/ooc.rst
- pomegranate/BayesianNetwork.pyx
- pomegranate/distributions/DiscreteDistribution.pyx
- pomegranate/distributions/GammaDistribution.pyx
- pomegranate/hmm.pyx
No one should be using Python 2 anymore, and creating aliases for the range and zip functions prevents the Cython compiler from replacing those functions with optimized C code.
When putting parentheses around the arguments to the print function, I have preserved the extra spaces in files that use that convention when calling functions, and left them out in files that generally do not use that convention.
I have not attempted to update any of the Jupyter notebooks.
> Drop support for Python 2

- pomegranate/hmm.pyx
Currently HiddenMarkovModel.to_json is totally broken because the modules it depends on are not imported correctly.
> Fix math and json imports in hmm.pyx

- pomegranate/utils.pxd
- pomegranate/utils.pyx
This both makes the code easier to read and avoids using calloc without a matching call to free.
> Define GPU and has_cupy as bints

- pomegranate/BayesianNetwork.pyx
- pomegranate/FactorGraph.pyx
- pomegranate/hmm.pyx
- pomegranate/kmeans.pyx
In the same vein as #655 and #723, this commit speeds up various functions by eliminating unnecessary memory operations.
> Don't use numpy.zeros for memory that is about to be reinitialized

- pomegranate/distributions/ConditionalProbabilityTable.pyx
- pomegranate/distributions/DiscreteDistribution.pyx
- pomegranate/distributions/JointProbabilityTable.pyx
This reverts commit f5f387c8f2ecf6ef5c2be74764b479194ebae4a6.
That was a mistake, sorry. `Distribution.from_json` depends on the dtype starting with `numpy.` if it is a numpy type.
> Revert "Use type.__name__ instead of str(type) and string manipulation (#728)"

- tests/test_bayes_net.py
These tests would have caught the problem with my last pull request.
> Test that data types are preserved in JSON deserialization

- pomegranate/utils.pyx
Adding an explicit casting of input array to C-layout in the utils check_input method (see #717 ) not sure if this is a full fix, as there might be some places where the method is not used.
> added explicit casting of input X to C-layout

- pomegranate/distributions/JointProbabilityTable.pxd
- pomegranate/distributions/JointProbabilityTable.pyx
This commit removes code that was unnecessarily copied and pasted from ConditionalProbabilityTable to JointProbabilityTable, which results in cleaner code, less memory usage, and a slight speed improvement to Bayes net predictions.
> Remove unused variables from JointProbabilityTable class

- pomegranate/kmeans.pyx
This is a follow-up to commit cafeee45bec517d479e2579e6ee5169eb94b8103.
> Ensure that multidimensional k-means input arrays are in C order

- pomegranate/distributions/distributions.pyx
It's best to be explicit about this so that other namespaced types can be supported in the future.
> Check that the JSON dtype is a numpy type before treating it as such

- pomegranate/FactorGraph.pyx
- pomegranate/MarkovNetwork.pyx
- pomegranate/base.pyx
- pomegranate/distributions/DiscreteDistribution.pyx
This is the wad of memory cleanups that I found while investigating other performance improvements.
> Get rid of a couple more calls to calloc and numpy.zeros

- pomegranate/distributions/DiscreteDistribution.pyx
This decreases the time required to make Bayes net predictions by about 35% by exploiting the fact that the keys of the two distributions being compared or multiplied are usually identical.
Test program:
```
```
Before:
```
mean   0.002968  0.002968
max    0.003024  0.003377
std    0.000013  0.000060
```
After:
``` …
```
> Add fast paths for comparing and multiplying discrete distributions

- pomegranate/FactorGraph.pyx
This is a simple change that decreases the time required to make Bayes net predictions by about 7%.
Test program:
```
```
Before:
```
mean   0.002968  0.002968
max    0.003024  0.003377
std    0.000013  0.000060
```
After:
``` …
```
> Skip convergence checks after the first failed check

- pomegranate/utils.pyx
This makes Bayes net predictions about 37% faster.
Test program:
```
```
Before:
```
mean   0.002025  0.002019
max    0.002062  0.002119
std    0.000007  0.000016
```
After:
```
mean   0.001275  0.001270
max    0.001294 …
```
> Use C isnan function instead of numpy.isnan in _check_nan

- pomegranate/distributions/ConditionalProbabilityTable.pxd
- pomegranate/distributions/ConditionalProbabilityTable.pyx
- pomegranate/distributions/JointProbabilityTable.pxd
- pomegranate/distributions/JointProbabilityTable.pyx
This is really just a code cleanup: OrderedDict is deprecated because Python dicts are guaranteed to be ordered from Python 3.5 on. For what it's worth though, the switch does make Bayes net predictions 1-3% faster.
> Use regular dict instead of OrderedDict

- pomegranate/distributions/DiscreteDistribution.pyx
This patch makes `DiscreteDistribution.__mul__` look more like `DiscreteDistribution.equals`, which helps make clear that the same shortcut logic is being used in both functions. Plus, when combined with the [isnan improvement I sent earlier](https://github.com/jmschrei/pomegranate/pull/761), moving the assertion improves performance by 1-2% when making predictions from a Bayes net.
Test program:
```
```
With isnan improvement only:
``` …
```
> Move assertion after shortcut in DiscreteDistribution.__mul__

- pomegranate/FactorGraph.pyx
This reduces the time required to make Bayes net predictions by about 2%.
Test program:
```
```
Before:
```
mean   0.001286  0.001286
max    0.001304  0.001318
std    0.000005  0.000006
```
After:
```
mean   0.001258 …
```
> Avoid using numpy slices in FactorGraph.predict_proba

- pomegranate/bayes.pyx
- pomegranate/hmm.pyx
All concrete implementations of Model._log_probability fill the entire
array, so zeroing it out beforehand is a waste of time.
> Don't initialize logp before calling Model._log_probability on it

- pomegranate/BayesianNetwork.pyx
These two variables were initialized to those values right before the if statement.
> Remove redundant assignments from BayesianNetwork.generate_parent_graph

- pomegranate/BayesianNetwork.pyx
I noticed this a while back and totally forgot to send a fix.
> Remove unused variable is_na from discrete_score_node

- pomegranate/BayesianNetwork.pyx
- pomegranate/MarkovChain.pyx
- pomegranate/MarkovNetwork.pyx
- pomegranate/bayes.pyx
- pomegranate/distributions/ConditionalProbabilityTable.pyx
- pomegranate/distributions/IndependentComponentsDistribution.pyx
- pomegranate/distributions/KernelDensities.pyx
- pomegranate/distributions/distributions.pyx
- pomegranate/gmm.pyx
- pomegranate/io.py
- pomegranate/kmeans.pyx
- pomegranate/parallel.pyx
- pomegranate/utils.pyx
numpy.array always makes a copy whereas numpy.asarray only makes a copy if necessary.
Compare:
```
$ /usr/bin/time -v python -c 'import numpy as np; np.array(np.ones(1000000))' 2>&1 | grep 'Maximum resident set'
Maximum resident set size (kbytes): 41096
```
```
$ /usr/bin/time -v python -c 'import numpy as np; np.asarray(np.ones(1000000))' 2>&1 | grep 'Maximum resident set'
Maximum resident set size (kbytes): 33168
```
> Use numpy.asarray instead of numpy.array where possible

- pomegranate/BayesianNetwork.pyx
X_int can only contain small positive integers or NaN, so double precision is unnecessary.
This saved me about 80 MB of memory on a large test net, which translates to a savings of 7 GB when we're running 88 large nets at a time. That will definitely help us stay within our memory constraints.
Test program (start with `/usr/bin/time -v`):
```
import itertools as it
X = np.array(list(it.product([0,1], repeat=20)))
BayesianNetwork().from_samples(X, algorithm='chow-liu')
```
Before:
```
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:24.00
Maximum resident set size (kbytes): 1841372
```
After:
```
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:21.29
Maximum resident set size (kbytes): 1759564
```
> Store X_int in 32-bit precision when possible

- pomegranate/hmm.pyx
Without this check predict() will always return the `viterbi` method if the algorithm is anything but `map`
> check hmm algorithm validity

- benchmarks/benchmark_hmm.py
- pomegranate/hmm.pyx
- tests/test_hmm.py
In https://github.com/jmschrei/pomegranate/issues/802 i proposed adding transcoding of input sequences in hmm.fit to avoid invoking _check_input in hmm.summarize. This fix speed up fitting HMM models about two times.
With fix:
```
[1] Improvement: 253389.81343831721	Time (s): 0.2847
[2] Improvement: 213.1332476385287	Time (s): 0.2908
[3] Improvement: 76.93109403923154	Time (s): 0.2974
[4] Improvement: 44.39238843484782	Time (s): 0.283
[5] Improvement: 28.537198789825197	Time (s): 0.2837
[6] Improvement: 17.950176118465606	Time (s): 0.2804
[7] Improvement: 11.243089165887795	Time (s): 0.2813
[8] Improvement: 7.315842745301779	Time (s): 0.2797
Total Training Improvement: 253789.3164752493
Total Training Time (s): 2.9646
```
With pomegranate 0.13.4:
```
[1] Improvement: 253389.81343831721 …
```
> Optimization of HMM fitting.

- pomegranate/BayesClassifier.pyx
- pomegranate/BayesianNetwork.pyx
- pomegranate/FactorGraph.pyx
- pomegranate/MarkovChain.pyx
- pomegranate/MarkovNetwork.pyx
- pomegranate/NaiveBayes.pyx
- pomegranate/base.pyx
- pomegranate/distributions/ConditionalProbabilityTable.pyx
- pomegranate/distributions/DiscreteDistribution.pyx
- pomegranate/distributions/IndependentComponentsDistribution.pyx
- pomegranate/distributions/JointProbabilityTable.pyx
- pomegranate/distributions/MultivariateGaussianDistribution.pyx
- pomegranate/distributions/distributions.pyx
- pomegranate/gmm.pyx
- pomegranate/hmm.pyx
- pomegranate/kmeans.pyx
This decreases the time required to load a 5 MB Bayes net from JSON by about 33%, while at the same time it cleans up the code by factoring out JSON serialization and deserialization logic that is common to all models.
Test program:
```
from neurtu import Benchmark, delayed
json = open('test.json').read()
load_net = delayed(BayesianNetwork.from_json)(json)
print(Benchmark(wall_time=True, cpu_time=True, repeat=100)(load_net))
```
Before:
```
mean   0.296894  0.294889
max    0.303662  0.299657
std    0.002196  0.002272
```
After:
``` …
```
> Add (from|to)_dict methods for fast, reusable (de)serialization

- pyproject.toml
- setup.py
[[845](https://github.com/jmschrei/pomegranate/issues/845)] Installation via pip while missing cython fails
See https://setuptools.readthedocs.io/en/latest/build_meta.html and https://github.com/pypa/setuptools/issues/1317#issuecomment-387702371
> Tell Pip to install Cython, NumPy, and SciPy before running setup.py

- pomegranate/distributions/MultivariateGaussianDistribution.pyx
`calloc` already filled the arrays with zeros.
> Remove unnecessary memset calls from MultivariateGaussianDistribution

- pomegranate/base.pyx
- pomegranate/distributions/ConditionalProbabilityTable.pyx
- pomegranate/distributions/DiscreteDistribution.pyx
- pomegranate/distributions/JointProbabilityTable.pyx
- pomegranate/hmm.pyx
- pomegranate/kmeans.pyx
- pomegranate/utils.pyx
All C variables are guaranteed to be initialized to 0 before `__cinit__` is called, and all Python variables are guaranteed to be initialized to None before `__init__` is called.
See https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#initialisation-methods-cinit-and-init
I didn't change any behavior, but I did think it was strange that the JointProbabilityTable and ConditionalProbabilityTable constructors does not use their `frozen` parameters. Is that intentional?
> Remove redundant initializations from constructors

- pomegranate/BayesianNetwork.pyx
Recently we've been getting out-of-memory errors despite using the greedy algorithm instead of the exact one. This one-line fix cuts the greedy algorithm's memory usage in half, making it much more practical.
Test program:
```
X = load_digits(return_X_y=True)[0][:100,:25]
BayesianNetwork().from_samples(X, algorithm='greedy')
```
Before:
```
$ /usr/bin/time -v python test.py 2>&1 | grep 'Maximum resident set'
Maximum resident set size (kbytes): 8116744
```
After:
```
$ /usr/bin/time -v python test.py 2>&1 | grep 'Maximum resident set'
Maximum resident set size (kbytes): 4160728
```
> Free old parent graphs in BayesianNetwork.discrete_greedy

- pomegranate/BayesianNetwork.pyx
I just noticed that these variables aren't doing anything. It would make the code simpler and more understandable to simply remove them.
> Remove unused variables from ParentGraph class

- pomegranate/BayesianNetwork.pyx
`numpy.float` is deprecated and triggers the following warning in NumPy 1.20:
```DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.```
> Change numpy.float to numpy.float64

- pomegranate/BayesianNetwork.pyx
- pomegranate/FactorGraph.pyx
- pomegranate/distributions/MultivariateGaussianDistribution.pyx
- pomegranate/hmm.pyx
- pomegranate/kmeans.pyx
- pomegranate/utils.pyx
- setup.py
[According to Python's documentation](https://docs.python.org/3/reference/import.html#importsystem), import statements only import the named module once even if they are in a function that is called over and over. So moving the pygraphviz and matplotlib imports into the functions that use them should not cause any negative side effects, and it saves about 40 megabytes of RAM when they are not being used. 40 megabytes may not seem like much, but when you have 32 parallel processes all training Bayes nets, it adds up fast ;-)
Test program:
```
X = load_digits(return_X_y=True)[0][:100,:5]
BayesianNetwork().from_samples(X, algorithm='greedy')
```
Before:
```
$ /usr/bin/time -v python test.py 2>&1 | grep 'Maximum …
```
> Import pygraphviz, matplotlib, and cupy only when necessary

- pomegranate/hmm.pyx
This fixes the compilation warning `pomegranate/hmm.pyx:913:31: Index should be typed for more efficient access`
> Use a typed index in HiddenMarkovModel.bake

- pomegranate/utils.pyx
`numpy.float` is just a reference to the built-in `float`:
```
$ python3 -c 'import numpy; print(numpy.float is float)'
True
```
I missed this one in pull request #869.
> Remove reference to numpy.float from _check_nan

- pomegranate/kmeans.pyx
there doesn't seem to be much point in doing multiple different initialisations if using the same first-k starting points each time.
> Kmeans - only do one init if init method is first-k

- pomegranate/utils.pyx
- tests/test_gmm.py
If an ICD has a mixture of ``DiscreteDistribution`` and other distribution types then the discrete distributions have a keymap for encoding, and the other distributions get an empty keymap (based on initialization of keymaps per component as empty dicts). When data is then passed in the check_array uses keymaps to encode the data, but fails for the non-``DiscreteDistribution`` columns since they have empty keymaps. If the column has data for a non-``DiscreteDistribution`` it is numeric and doesn't require encoding -- the entire column can simply be cast to ``float64``. This PR makes a minimal alteration to work by columns first, and, in the case of an empty keymap attempts to cast the entire column to ``float64``. This resolves the issues seen in #947 . A test of this is also added.
Note: …
> Fix for #947: Be more flexible in ICD keymaps

- pomegranate/bayes.pyx
- tests/test_bayes_classifier.py
- tests/test_distributions.py
The `NaiveBayes` class can not be unpickled because the `__reduce__` method doesn't match the `__init__` constructor, as described in issue [#953](https://github.com/jmschrei/pomegranate/issues/953). This pull request fixes this bug, with accompanying unit test. In addition, it includes a `BetaDistribution` pickling unit test (which was missing).
> [#953]: Fixed BayesModel unpickling bug.

- pomegranate/BayesianNetwork.pyx
For issue #962.
Switch parallelism backend to multiprocessing, and fix the passing of kwargs for `log_probability()` and `predict_proba()`.
The following has succeeded:
```bash
python -m build
python setup.py test
```
Test environment:
> EC2 Amazon Linux (m5.2xlarge)
Python 3.8.8 (Cython)
pomegranate 0.14.8
Performance check (5,236 test instances):
`m` = `max_iterations`
`n` = `n_jobs`
| m\n | 1 | 2 | 4 |
| --- | --- | --- | --- | 
| 1 | 125s | 75s | 60s |
| 5 | 869s | 461s | 241s |
> Threading -> multiprocessing for Bayesian Network

- pomegranate/_utils.py
- pomegranate/hmm/_base.py
- tests/hmm/test_dense_hmm.py
- tests/test_utils.py
This is a proposal on how to fix #1018 .
It basically forwards the number of states to `partition_sequence` to check the correct shape for the priors.
So far I only tested that this will not raise an error. I did not check, if the priors are used correctly in training.
Note: This also includes the fix proposed in #1017. If this PR is merged #1017 can be closed. If #1017 is merged separably, this PR needs to be rebased
> Fix hmm fit shape check

- pomegranate/bayesian_network.py
- tests/test_bayesian_network.py
- tests/test_bayesian_network_structure_learning.py
A fix for the issue described in [issue 1058](https://github.com/jmschrei/pomegranate/issues/1058). I've patched the function and the tests and they work on nixos and Fedora.
> Fixing the _categorical_exact function and the tests to be more deterministic

- pomegranate/bayesian_network.py
- tests/test_bayesian_network.py
- tests/test_bayesian_network_structure_learning.py
This typo would cause the function to error if there was only a single shortest path.
> Fix typo in the _categorical_exact function

- docs/api.rst
Proposal to fix API rendering issue in the documentation, as described in #1040 .
The proposed implementation uses `autoclass `in place of `automodule`. 
In addition to that, I split `Distributions` and `Models` sections, which results in the following rendering:
> Fix API docs rendering

- pomegranate/gmm.py
This fixes a bug that empirically lowers the quality of the initialization.
When initializing gmm from weighted samples, the priors should be proportional to the sum of sample weights.
> Fix gmm initialization from weighted samples

- pomegranate/_utils.py
- pomegranate/distributions/normal.py
This is a proposal on how to fix https://github.com/jmschrei/pomegranate/issues/1036.
It makes some operations more generic to consider both vector tensor and scalar tensor.
It also implements estimating spherical covariances based on https://github.com/scikit-learn/scikit-learn/blob/364c77e047ca08a95862becf40a04fe9d4cd2c98/sklearn/mixture/_gaussian_mixture.py#L258.
> fit normal distribution when covariance_type == 'sphere'

- pomegranate/_utils.py
While playing around with pomegranate v1 I run into this warning:
`
/home/josalhor/Desktop/data-synt/venv/lib/python3.11/site-packages/pomegranate/_utils.py:62: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
`
I think my pull requests fixes that warning and should speed up the casting.
> Efficient Tensor conversion from list of numpy arrays

- pomegranate/distributions/normal.py
In the file distributions.normal, in the summarize function the input data was casted to tensor and the sample_weights were not. This raised an error later when computing self._xw_sum
> Fixed sample_weights not casted to tensor in Normal distribution
