pomegranate/hmm.pyx
Hi Jacob,
I accidentally introduced a simple dumb mistakes in my previous PR.
-Joe
=> Small mistake

benchmarks/benchmark_distributions.py, pomegranate/BayesianNetwork.pyx, pomegranate/base.pxd, pomegranate/distributions.pxd, pomegranate/distributions.pyx, pomegranate/gmm.pyx, pomegranate/utils.pxd, pomegranate/utils.pyx, requirements.txt, tests/test_distributions.py
```
MASTER
DISTRIBUTION BENCHMARKS
-----------------------
LOG PROBABILITY (N=10,000,000 iterations, N=100,000 FOR MVG)
UniformDistribution      : 1.648s
NormalDistribution       : 1.945s
LogNormalDistribution    : 3.426s
ExponentialDistribution  : 1.714s
GammaDistribution        : 5.351s
GaussianKernelDensity    : 23.44s
UniformKernelDensity     : 24.36s
TriangleKernelDensity    : 21.32s
MixtureDistribution      : 69.88s
DiscreteDistribution     : 1.746s
IndependentComponentsDistribution: 15.03s
MultivariateGaussianDistribution: 6.966s
TRAINING (N=1,000 ITERATIONS, BATCHES=10,000 ITEMS)
UniformDistribution      : 0.02648s
NormalDistribution       : 0.09814s
LogNormalDistribution    : 0.5827s
ExponentialDistribution  : 0.06633s
GammaDistribution        : 0.4169s
GaussianKernelDensity    : …
```
=> [MRG] Enhance distributions by removing the GIL 

pomegranate/BayesianNetwork.pyx, pomegranate/distributions.pyx, requirements.txt, tests/test_bayes_net.py, tests/test_distributions.py, tests/test_fsm.py, tests/test_hmm_training.py, tests/test_huge_monty_hall.py, tests/test_profile_hmm.py, tests/test_titanic.py
This pull requests add an imputation method to BayesianNetworks, which allows them to take in a matrix of data with missing values, and impute the most likely value given the structure and emissions of the network.
=> [WIP] BayesianNetwork imputation

pomegranate/BayesianNetwork.pyx, pomegranate/FactorGraph.pyx, pomegranate/base.pyx, pomegranate/distributions.pyx, pomegranate/fsm.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx, pomegranate/utils.pxd, pomegranate/utils.pyx
I've significantly cleaned up the tops of the files, removing extraneous imports which had built up because I simply copied the headers when starting new files. No new functionality is proposed. I've also added relative imports instead of absolute imports for imports from within this package, to make the logic easier to understand.
=> [MRG] ENH imports reduced

pomegranate/distributions.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx
Add a sklearn interface to GMM, HMM, and distribution models, in terms of fit, predict, and predict_proba. Also add unit tests to GMM, and make it a little faster. This should probably be two PRs but w/e.
=> sklearn interface

benchmarks/benchmark_hmm.py, pomegranate/hmm.pyx
This passes the distributions as a void array so that we don't need to acquire the gil inside Baum-Welch to unpack them. It also removes acquiring the gil to modify the expected transitions matrix. This performs slightly better, increasing speed from ~x1.8 to ~x2.4 faster with 4 cores. There is more work to be done, but this is another good step in the right direction.
=> ENH removed gil requiring time

pomegranate/hmm.pyx
```
HIDDEN MARKOV MODEL BENCHMARKS
gaussian emissions
FORWARD-BACKWARD (master): time: 34.526
FORWARD-BACKWARD (branch): time: 8.0326
multivariate gaussian emissions
FORWARD-BACKWARD (master): time: 77.954
FORWARD-BACKWARD (branch): time: 8.1383
discrete distribution
FORWARD-BACKWARD (master): time: 17.787
FORWARD-BACKWARD (branch): time: 15.196
```
Much faster now.
=> [MRG] forward_backward faster

README.md
Just a small change: I added syntax highlighting to all python code blocks in the README.md - makes them easier to read.
=> Add syntax highlighting to readme.md

pomegranate/NaiveBayes.pyx, pomegranate/__init__.py, setup.py
Basic Naive Bayes classifier using these models, or any model which exposes a `log_probability` and `fit` method. This acts as a supervised version of general mixture models because labels are explicitly stated instead of inferred in the expectation step of EM.
=> Naivebayes

pomegranate/utils.pxd, pomegranate/utils.pyx
Remove inline functions, since they seem to be causing problems with installation.
=> inline removal

examples/hmm_rainy_sunny.ipynb
added notebook for hmm_rainy_sunny.py
=> ENH rainy-sunny notebook

pomegranate/NaiveBayes.pyx, pomegranate/distributions.pyx
New initialization for Naive Bayes, so you don't need to waste time putting phony parameters in. Also adds a `from_samples` method (as opposed to `from_sample`) as a class method for most distributions so that you don't need to put fake parameters in for them either.
=> Distribution infer

examples/naivebayes_hmm_cheating_coin_toss.ipynb, examples/naivebayes_multivariate_male_female.ipynb, examples/naivebayes_simple_male_female.ipynb
Created ipython notebook examples to demonstrate how to use pomegranate's naive bayes classifier. Examples included usage of a normal distribution, multivariate gaussian distribution, and hidden markov models.
=> ENH created new naive bayes ipython notebook examples

pomegranate/BayesianNetwork.pyx, pomegranate/distributions.pxd, pomegranate/distributions.pyx
Increases speed of updating both joint and conditional probability tables.
=> ENH bayes speed

pomegranate/NaiveBayes.pyx
Doesn't require the input to naive bayes is a numpy array. Useful when dealing with Naive Bayes of HMMs.
=> ENH naive bayes

MANIFEST, pomegranate/base.pyx, pomegranate/distributions.pyx, pomegranate/fsm.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx, setup.py
Produce neater jsons in the manner suggested in #17
=> ENH json formatting

pomegranate/hmm.pyx
The graph object in the HMM wasn't updating after training, making it so writing the model out to a file wasn't capturing the trained parameters. Now the graph object updates after training.
=> FIX graph update

pomegranate/hmm.pyx
Add a deep copy method to HMMs.
=> ENH deep copy method added

docs/naivebayes.md, mkdocs.yml
Created documentation showing how to use methods for naive bayes for read the docs.
=> [MRG +1] Naive Bayes Documentation

tests/test_naive_bayes.py
Created unittests for naive bayes methods. Currently tests constructors and methods using a univariate distribution, bivariate distribution, and hidden markov models.
=> ENH unittests for naive bayes

pomegranate/distributions.pxd, pomegranate/distributions.pyx, tests/test_distributions.py
Added the poisson distribution.
=> ENH added poisson distribution

pomegranate/MarkovChain.pyx, pomegranate/__init__.py, pomegranate/distributions.pxd, pomegranate/distributions.pyx, pomegranate/hmm.pyx, setup.py
Add Markov Chain as a model, and update both conditional and joint probability tables.
=> [MRG] Markov Chain

pomegranate/BayesianNetwork.pyx, tests/test_huge_monty_hall.py
More documentation for Bayes nets.
=> ENH Bayes Net doc

pomegranate/gmm.pyx, tests/test_gmm.py
Improvements to the GMM module, better API, numpy docs.
=> GMM documentation and internals improvement

pomegranate/hmm.pyx
Should fix the memory leak issues pointed out in #95
=> FIX memoryleak hmm

pomegranate/MarkovChain.pyx, pomegranate/fsm.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx, tests/test_hmm_training.py, tests/test_profile_hmm.py
Add a significant amount of documentation as well as fixing a memory leak in HMMs.
=> ENH documentation/memoryleak

tests/test_markov_chain.py, tests/test_naive_bayes.py
Created a unit test for markov chains. Currently implements first and second order markov chains. Also edited naive bayes's unit test in order to reflect the changes to the code and add some error testing.
=> Unit Tests for Markov Chains

pomegranate/gmm.pyx
pomegranate seems to require 2D data arrays.
Someone please confirm that my edit here matches what the documentation author intended...
=> Fix GMM example more

pomegranate/hmm.pyx
Adds 4 frees to the end of _viterbi() function clearing allocated memory
=> Fix memory leak

pomegranate/NaiveBayes.pyx, pomegranate/utils.pyx, tests/test_naive_bayes.py
Added a conversion method and error handling to check for proper dimensions in input data.
Added a dimension variable to naive bayes.
=> ENH added error handling and dimension checks to naive bayes

pomegranate/NaiveBayes.pyx
created a simple to and from json method as well as a print method for naive bayes.
=> ENH added basic json and print methods to naive bayes

pomegranate/BayesianNetwork.pyx, pomegranate/NaiveBayes.pyx, pomegranate/base.pxd, pomegranate/base.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx, tests/test_gmm.py, tests/test_hmm.py, tests/test_naive_bayes.py
Added d variable to hmm, naive bayes, gmm, and bayes net. Edited implementation to remove redundant variables to include more dimension checks. Edited some unit tests to reflect these changes.
=> Added dimension tracking variable

pomegranate/gmm.pyx, pomegranate/hmm.pyx
=> Change to models

pomegranate/hmm.pyx
support training HMMs using weighted observations
=> Hmm weighted training

MANIFEST, pomegranate/BayesianNetwork.pyx, pomegranate/base.pyx, pomegranate/distributions.pxd, pomegranate/distributions.pyx
Improves the implementation of ConditionalProbabilityTable's and JointProbabilityTable's, and adds in a cython level backend.
=> ENH CPT/JPT

.gitignore
I added some entries to the gitignore specific to mac / emacs.
=> add entries to gitignore

.travis.yml
Noticed that you never got around to doing it, this should fix it.
=> unpin joblib version and install with conda

pomegranate/BayesianNetwork.pyx
Adds a fast exact algorithm for Bayesian network structure learning from Malone 2011 which uses dynamic programming to make the learning task 'merely exponential'.
=> ENH fast bayesian network structure learning

pomegranate/BayesianNetwork.pyx
Allow more efficient learning of Bayesian networks through a constraint graph.
=> Bayesian Network Constraint Graph learning

pomegranate/base.pyx, pomegranate/gmm.pyx, pomegranate/kmeans.pyx, tests/test_gmm.py
beautified gmm and kmeans + small fix of gmm.__reduce__ with regression test.
=> beautification

pomegranate/BayesianNetwork.pyx
Implementation of suggested change in issue #204
=> Set meaningful state names for network learned from data

pomegranate/hmm.pyx, tests/test_hmm_training.py
Allow for training of HMMs on labeled sequences (also significantly clean up the backend for Viterbi calculations and training)
=> ENH labeled training

pomegranate/BayesianNetwork.pyx, tests/test_bayes_net.py
1. it doesn't modify input observations now and always return a numpy.ndarray
2. it identify np.nan as missing value correctly
#214
=> BayesianNetwork.predict change:

tests/test_distributions.py
Added a unit test to cover the Bernoulli Distribution
=> [MRG] bernoulli tests

pomegranate/distributions.pxd, pomegranate/distributions.pyx, tests/test_distributions.py
Adding vectorized calculations for all distributions to make use of the fast internals when calculating many log/probabilities.
=> Vectorized distributions

docs/BayesianNetwork.rst, docs/Distributions.rst, docs/GeneralMixtureModel.rst, docs/HiddenMarkovModel.rst, docs/MarkovChain.rst, docs/NaiveBayes.rst
Documentation update for recent API changes.
=> [MRG] readthedocs update

pomegranate/distributions.pyx, pomegranate/utils.pxd, pomegranate/utils.pyx
This PR adds GPU support for multivariate Gaussian distributions in all models.
=> [MRG] GPU support

pomegranate/BayesClassifier.pyx, pomegranate/BayesianNetwork.pyx, pomegranate/NaiveBayes.pyx, pomegranate/distributions.pxd, pomegranate/distributions.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx, pomegranate/kmeans.pyx, tests/test_naive_bayes.py
Adding explicit n_jobs parameter to each `fit` and `from_samples` method that is far more linearly scalable than the previous hacky implementation.
Old HMM:
```
Hidden Markov Model (1 job)
[1] Improvement: 243741.875938	Time (s): 4.94
[2] Improvement: 8148.72182169	Time (s): 4.95
[3] Improvement: 4067.39413681	Time (s): 4.96
[4] Improvement: 2416.07915712	Time (s): 5.04
[5] Improvement: 1589.95958247	Time (s): 4.95
Total Training Improvement: 259964.030636
Total Training Time (s): 29.71
Hidden Markov Model (2 jobs)
[1] Improvement: 192887.359244	Time (s): 2.93
[2] Improvement: 9266.85577237	Time (s): 2.92
[3] Improvement: 4629.36550196	Time (s): 2.91
[4] Improvement: 2759.31593903	Time (s): 2.94
[5] Improvement: 1822.96337097	Time (s): 2.84
Total Training Improvement: 211365.859828
Total …
```
=> [MRG] Refactor data parallel fitting backend

docs/gpu.rst, docs/index.rst, docs/install.rst, docs/ooc.rst, docs/parallelism.rst, docs/semisupervised.rst
This will expand greatly the documentation on the ReadTheDocs page, including a topic specific FAQ to help users efficiently use pomegranate.
=> [MRG] Improvement to ReadTheDocs

docs/whats_new.rst, pomegranate/BayesianNetwork.pyx, pomegranate/FactorGraph.pyx, pomegranate/kmeans.pyx, pomegranate/utils.pyx, tests/test_bayes_net.py
This PR cleans up the Bayesian network code a little bit, factors out the data checking function, vectorizes and adds n_jobs to `predict_proba`, and adds a bunch of new unit tests to ensure proper functionality. Should resolve #365
=> [MRG] Cleanup Bayesian Network code

docs/callbacks.rst, docs/index.rst, docs/install.rst, docs/whats_new.rst, pomegranate/BayesClassifier.pyx, pomegranate/NaiveBayes.pyx, pomegranate/bayes.pyx, pomegranate/callbacks.py, pomegranate/gmm.pyx, pomegranate/hmm.pyx, tests/test_gmm.py, tests/test_hmm.py
This adds callbacks in the same manner as Keras, as functionality that get executed at the beginning of training, the end of training, or at the end of each epoch. Users can use the built-in ones, including History, ModelCheckpoint, CSVLogging, or LambdaCallback, or write their own.
=> [MRG] Add callback functionality

setup.py
Also add all pxd files for declarations.
=> Add distributions subpackage

pomegranate/distributions/UniformDistribution.pyx, pomegranate/hmm.pyx
=> Missing numpy import in UniformDistribution.pyx

docs/whats_new.rst, pomegranate/base.pyx, requirements.txt, setup.py, tests/test_hmm.py
YAML is a superset of JSON that is 4 to 5 times more compact which makes
it easier to inspect visually.  To use it you have to make sure the yaml
package is installed.
=> Add to_yaml convenience functions

pomegranate/BayesianNetwork.pyx, pomegranate/distributions/JointProbabilityTable.pyx, pomegranate/distributions/MultivariateGaussianDistribution.pyx
Mismatches found with:
git grep 'calloc(\|free('
=> More memory leak fixes as in #450

docs/Distributions.rst
- Add wording that explains to use IndependentComponentsDistribution
when no correlation
- Add all distributions to API doc
See comment in #432
=> Add correlation comments in multivariate docs

docs/whats_new.rst, rebuildconda
This script will rebuild a conda environment given a python version.
=> Add rebuildconda convenience script

pomegranate/bayes.pyx, pomegranate/distributions/BernoulliDistribution.pyx, pomegranate/distributions/BetaDistribution.pyx, pomegranate/distributions/ConditionalProbabilityTable.pyx, pomegranate/distributions/DirichletDistribution.pyx, pomegranate/distributions/DiscreteDistribution.pyx, pomegranate/distributions/ExponentialDistribution.pyx, pomegranate/distributions/GammaDistribution.pyx, pomegranate/distributions/IndependentComponentsDistribution.pyx, pomegranate/distributions/JointProbabilityTable.pyx, pomegranate/distributions/KernelDensities.pyx, pomegranate/distributions/LogNormalDistribution.pyx, pomegranate/distributions/MultivariateGaussianDistribution.pyx, pomegranate/distributions/NormalDistribution.pyx, pomegranate/distributions/PoissonDistribution.pyx, pomegranate/distributions/UniformDistribution.pyx, pomegranate/hmm.pyx, pomegranate/utils.pyx, tests/test_distributions.py, tests/test_gmm.py, tests/test_hmm.py
This PR should allow all models to deterministically sample through passing in a random seed in a style similar to sklearn, i.e., by passing either an integer or a numpy.random.RandomState object through the `random_state` parameter of each `sample` method.
Example:
```python
>>> d = NormalDistribution(5, 2)
>>> d.sample(random_state=0)
8.528104691935328
```
=> [MRG] Add in deterministic sampling

docs/install.rst
Trivial fix to reflect new requirements.
=> Fix comment for networkx >= 2.0

pomegranate/BayesianNetwork.pyx
=> Fix calculation of h in BayesianNetwork.discrete_exact_a_star

.travis.yml, MANIFEST.in
similar to https://github.com/jmschrei/pomegranate/issues/548
This would help Debian out, thanks!
=> *.pxd *.pyx from pomegranate.distributions as well

pomegranate/bayes.pyx
This is another case of repeating code that was just executed a few lines before.
=> Fix copy-paste error in BayesModel.predict_log_proba

pomegranate/BayesianNetwork.pyx
=> Remove extraneous argument from discrete_exact_a_star call

docs/index.rst
Noticed at readthedocs: https://pomegranate.readthedocs.io/en/latest/
=> Fix CI badges

pomegranate/BayesianNetwork.pyx, pomegranate/MarkovNetwork.pyx
This change just makes the code a little simpler (it doesn't noticeably improve performance).
=> Get rid of mutual_info_ndarray

tests/test_bayes_net.py, tests/test_distributions.py, tests/test_profile_hmm.py
This fixes the i386 build on Debian.
=> Relax a few tests due to a very small rounding difference

pomegranate/hmm.pyx
Solves issue jmschrei/pomegranate#693
=> Replace HiddenMarkovModel constructors by cls in factory class methods

pomegranate/BayesianNetwork.pyx, pomegranate/MarkovNetwork.pyx, pomegranate/distributions/BernoulliDistribution.pyx, pomegranate/distributions/ConditionalProbabilityTable.pyx, pomegranate/distributions/DiscreteDistribution.pyx, pomegranate/distributions/JointProbabilityTable.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx, pomegranate/kmeans.pyx
Somehow I missed these in https://github.com/jmschrei/pomegranate/pull/655
=> More calloc and memset cleanup

pomegranate/distributions/ConditionalProbabilityTable.pyx, pomegranate/distributions/DiscreteDistribution.pyx, pomegranate/distributions/JointProbabilityTable.pyx
The code is a lot more understandable this way.
=> Use type.__name__ instead of str(type) and string manipulation

pomegranate/BayesClassifier.pyx, pomegranate/BayesianNetwork.pyx, pomegranate/FactorGraph.pyx, pomegranate/MarkovNetwork.pyx, pomegranate/NaiveBayes.pyx, pomegranate/bayes.pyx, pomegranate/gmm.pyx, pomegranate/hmm.pyx, pomegranate/kmeans.pyx, pomegranate/parallel.pyx, pomegranate/utils.pyx
This primarily makes the code easier to understand, but it can also reduce the time it takes for scripts to start up as well as reducing the amount of memory they consume.
=> Remove unused imports

pomegranate/FactorGraph.pyx
There are three big changes here:
1. Don't update messages leaving marginal nodes if the distributions converged after a single iteration.
2. Don't deep-copy the distributions again if the maximum number of iterations has been reached.
3. Stop searching for the message to be set if it has already been found.
These shortcuts reduce the time required to make Bayes net predictions on random data by about 8%.
Test program:
```
#!/usr/bin/env python3
X = np.round(np.random.rand(10000, 14))
predict = delayed(net.predict_proba)({str(x): 0 for x in range(5)}, check_input=False)
```
Before:
``` …
```
=> Reorganize loops to avoid unnecessary steps in FactorGraph.predict_proba

pomegranate/BayesianNetwork.pyx
Changes reflect discussion from [#786](https://github.com/jmschrei/pomegranate/issues/786)
I have run the example code to verify its operation and have updated the printed output.
=> [786] Updated BayesianNetwork docstring to match current API

pomegranate/BayesianNetwork.pyx
=> FIX typo in documentation of from_samples

pomegranate/BayesianNetwork.pyx
Document filename param, and how to call plt.show() if not inside a %matplotlib inline environment. 
Also, suggest TODO for rendering direct to SVG.
=> Document BayesianNetwork.plot() - Addresses #844.

pomegranate/BayesianNetwork.pyx
Continuation of pull request #792
=> Eliminate unnecessary variable X_int_ptr from BayesianNetwork.summarize

pomegranate/BayesianNetwork.pyx
This change is just to make the code easier to read.
=> Use set.remove instead of set subtraction to remove a single item

pomegranate/BayesianNetwork.pyx, pomegranate/distributions/ConditionalProbabilityTable.pxd, pomegranate/distributions/ConditionalProbabilityTable.pyx, pomegranate/distributions/JointProbabilityTable.pyx, pomegranate/utils.pyx
The majority of this dead code appeared last summer.
=> Remove dead code

pomegranate/BayesianNetwork.pyx, pomegranate/utils.pyx
Clearly you and I both were thinking in C when we wrote these lines.
=> Remove superfluous semicolons at the ends of lines

pomegranate/BayesianNetwork.pyx, pomegranate/hmm.pyx, setup.py, tests/test_bayesian_network.py
This is a re-implementation of #875 that is more comprehensive and adds in unit tests.
=> [MRG] Add low_memory flag to BN
